### ISSUE TITLE
Can I use it on my dot files?

### ISSUE THREAD

**Issue by orlandosh** [ryo33/nvim-cmp-rust#1]
I just found this after googling some methods of sorting rust analyzer's autocomplete on nvim-cmp. They didn't feel productive by default and I'm amazed by the way you solved it.

my dot files are public https://github.com/orlandosh/dotfiles as I often share them with my friend, and also don't mind if people want to get some ideas or code from configurations as well.

I included your code without the `vim.iter` method as it's not available before 0.10, and I also added IntoSql (from diesel) to the list of fields.

I see that despite your repo being public, there's no license. Do you have any license you want me to include? Can I leave it the way it is?
Thank you!

**Comment by ryo33** [comment]
It's absolutely ok to use this, but I forgot to add licenses. I've added license files LICENSE-MIT and LICENSE-APACHE right now. Thank you for letting me notice that.

**Comment by orlandosh** [comment]
Thanks @ryo33! I really appreciate it!
I've updated the file to include your license https://github.com/orlandosh/dotfiles/blob/main/neovim/lua/autocomplete/rust_sorting.lua :)

**Comment by ryo33** [comment]
Looks nice! Have good days!
